/* EPS-TOPIK Vocabulary Quiz — vanilla JS */
(() => {
  'use strict';
  const KEY_PROGRESS='epsTopikProgress', KEY_SETTINGS='epsTopikSettings', KEY_HISTORY='epsTopikQuizHistory';
  const defaults={darkMode:false,timer:0,questionCount:'10',quizMode:'mixed'};
  const state={progress:load(KEY_PROGRESS,{xp:0,streak:0,bestStreak:0,highestScore:0,learned:{},mastered:{},flashcards:{},openedChapters:[],achievements:{} }),settings:load(KEY_SETTINGS,defaults),history:load(KEY_HISTORY,[]),quiz:null,flash:null};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function load(key,fallback){try{const x=JSON.parse(localStorage.getItem(key));return x??fallback}catch{return fallback}}
  function save(){localStorage.setItem(KEY_PROGRESS,JSON.stringify(state.progress));localStorage.setItem(KEY_SETTINGS,JSON.stringify(state.settings));localStorage.setItem(KEY_HISTORY,JSON.stringify(state.history))}
  function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function chapter(id){return chapters.find(c=>c.id===Number(id))}
  function chVocab(id){return vocabulary.filter(v=>v.chapter===Number(id))}
  function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
  function progressFor(id){const list=chVocab(id);if(!list.length)return 0;const mastered=list.filter(v=>state.progress.mastered[v.id]).length;return Math.round(mastered/list.length*100)}
  function xpLevel(){return Math.floor((state.progress.xp||0)/100)+1}
  function ensure(){state.progress.openedChapters ??=[]; state.progress.learned ??={};state.progress.mastered ??={};state.progress.flashcards ??={};state.progress.achievements ??={};}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
  function award(amount,msg){state.progress.xp=(state.progress.xp||0)+amount; if(msg)toast(`+${amount} XP — ${msg}`);}
  function markOpened(ch){if(!state.progress.openedChapters.includes(ch))state.progress.openedChapters.push(ch);checkAchievements();save()}
  function checkAchievements(){
    const a=state.progress.achievements;
    if(state.history.length)a.firstQuiz=true;
    if((state.progress.bestStreak||0)>=10)a.streak10=true;
    if(chapters.some(c=>chVocab(c.id).length && chVocab(c.id).every(v=>state.progress.mastered[v.id])))a.chapterMaster=true;
    if(state.history.some(h=>h.score===100))a.perfect=true;
    if(state.progress.openedChapters.length>=5)a.explorer=true;
  }
  function avgScore(){return state.history.length?Math.round(state.history.reduce((s,h)=>s+h.score,0)/state.history.length):0}
  function fmtTime(sec){const s=Math.max(0,Math.round(sec));return `${Math.floor(s/60)}m ${String(s%60).padStart(2,'0')}s`}
  function totalMastered(){return Object.keys(state.progress.mastered).length}
  function totalLearned(){return Object.keys(state.progress.learned).length}

  function setTheme(){document.documentElement.dataset.theme=state.settings.darkMode?'dark':'light';const b=$('#themeToggle');if(b)b.textContent=state.settings.darkMode?'☾':'☼'}
  function navActive(name){$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===name))}

  function clearQuizTimer(){ if(state.quiz?.timer){ clearInterval(state.quiz.timer); state.quiz.timer=null; } }
  function render(){ensure();setTheme();const hash=location.hash.replace(/^#/,'')||'home';
    if(!hash.startsWith('quiz') && hash!=='results' && hash!=='review') clearQuizTimer();
    if(hash.startsWith('quiz')){renderQuizSetup(Number(new URLSearchParams(hash.split('?')[1]||'').get('chapter')||1));return}
    if(hash==='results'){renderResults();return}
    if(hash==='review'){renderReview();return}
    if(hash.startsWith('flashcards')){renderFlashcards();return}
    if(hash==='chapters'){renderChapters();return}
    if(hash==='vocabulary'){renderVocabulary();return}
    if(hash==='statistics'){renderStatistics();return}
    renderHome();
  }

  function renderHome(){navActive('home');const recent=state.history.slice(-5).reverse();
    $('#main').innerHTML=`<section class="hero">
      <div><div class="eyebrow">EPS-TOPIK 한국어 어휘 퀴즈</div><h1><span class="ko">한국어 어휘 퀴즈</span></h1><p class="lead">Belajar dan menguji kosakata EPS-TOPIK Bab 1–30 secara interaktif. Semua data kosakata disimpan lokal sehingga quiz dapat berjalan tanpa backend.</p><div class="actions"><a class="btn primary" href="#chapters">Mulai Belajar</a><a class="btn secondary" href="#vocabulary">Daftar Kosakata</a></div></div>
      <div class="card"><div class="stat-label">Level</div><div class="stat-number">${xpLevel()}</div><div class="small">${state.progress.xp||0} XP</div><div style="height:12px"></div><div class="stat-label">Streak terbaik</div><div class="stat-number">${state.progress.bestStreak||0}</div></div>
    </section>
    <section class="section"><div class="grid stats-grid">
      ${statCard(chapters.length,'Total Bab')}${statCard(vocabulary.length,'Total Kosakata')}${statCard(state.history.length,'Quiz Diselesaikan')}${statCard(avgScore()+'%','Rata-rata Score')}
    </div></section>
    <section class="section"><div class="section-head"><div><h2>Lanjut Belajar</h2><p>Pilih bab untuk langsung membuka kosakata atau quiz.</p></div><a class="btn" href="#chapters">Lihat semua</a></div><div class="grid">${chapters.slice(0,6).map(chapterCard).join('')}</div></section>
    <section class="section"><div class="section-head"><div><h2>Quiz Terbaru</h2><p>Riwayat tersimpan di perangkat ini.</p></div></div>${recent.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Bab</th><th>Score</th><th>Benar</th></tr></thead><tbody>${recent.map(h=>`<tr><td>${esc(new Date(h.date).toLocaleString('id-ID'))}</td><td>Bab ${h.chapter}</td><td><strong>${h.score}%</strong></td><td>${h.correct}/${h.total}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Belum ada quiz. Mulai dari Bab 1.</div>'}</section>`;
  }
  function statCard(n,l){return `<div class="card"><div class="stat-number">${esc(n)}</div><div class="stat-label">${esc(l)}</div></div>`}
  function chapterCard(c){const list=chVocab(c.id),p=progressFor(c.id);return `<article class="card chapter-card"><div class="chapter-no">BAB ${String(c.id).padStart(2,'0')}</div><h3>${esc(c.titleKo)}</h3><div class="id">${esc(c.titleId)}</div><div class="meta">${list.length} kosakata</div><div class="progress-track" aria-label="Progress bab ${c.id}"><div class="progress-fill" style="width:${p}%"></div></div><div class="meta">Progress: <strong>${p}%</strong></div><div class="spacer"></div><div class="actions"><a class="btn secondary" href="#vocabulary?chapter=${c.id}">Belajar</a><a class="btn primary" href="#quiz?chapter=${c.id}">Quiz</a></div></article>`}
  function renderChapters(){navActive('chapters');$('#main').innerHTML=`<section class="section"><div class="section-head"><div><h2>Bab 01–30</h2><p>Jumlah kosakata dihitung otomatis dari data sumber.</p></div></div><div class="grid">${chapters.map(chapterCard).join('')}</div></section>`}

  function renderVocabulary(){navActive('vocabulary');const q=new URLSearchParams(location.hash.split('?')[1]||'');const selected=Number(q.get('chapter')||0);const cats=[...new Set(vocabulary.map(v=>v.categoryKo))];
    $('#main').innerHTML=`<section class="section"><div class="section-head"><div><h2>Vocabulary Explorer</h2><p>Cari Korea, Indonesia, kategori, nomor bab, atau judul bab.</p></div></div><div class="card toolbar"><input id="vSearch" class="input" placeholder="Cari misalnya petani atau 농부" aria-label="Cari vocabulary"><select id="vChapter" class="select"><option value="0">Semua Bab</option>${chapters.map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>Bab ${c.id} — ${esc(c.titleKo)}</option>`).join('')}</select><select id="vCategory" class="select"><option value="">Semua Kategori</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div style="height:14px"></div><div id="vResults"></div></section>`;
    const run=()=>{const s=($('#vSearch').value||'').trim().toLocaleLowerCase();const ch=Number($('#vChapter').value);const cat=$('#vCategory').value;const res=vocabulary.filter(v=>{const c=chapter(v.chapter);const hay=[v.korean,v.indonesian,v.categoryKo,v.categoryId,`bab ${v.chapter}`,c.titleKo,c.titleId].join(' ').toLocaleLowerCase();return(!s||hay.includes(s))&&(!ch||v.chapter===ch)&&(!cat||v.categoryKo===cat)});$('#vResults').innerHTML=res.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Korea</th><th>Indonesia</th><th>Bab</th><th>Kategori</th><th></th></tr></thead><tbody>${res.map(v=>`<tr><td><strong>${esc(v.korean)}</strong></td><td>${esc(v.indonesian)}</td><td>Bab ${v.chapter}</td><td>${esc(v.categoryKo)}</td><td><button class="btn secondary" data-learn="${esc(v.id)}">${state.progress.mastered[v.id]?'✓ Dikuasai':'Tandai'}</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Tidak ada kosakata yang cocok.</div>';$$('[data-learn]').forEach(b=>b.onclick=()=>{const id=b.dataset.learn;state.progress.learned[id]=true;state.progress.mastered[id]=!state.progress.mastered[id];save();b.textContent=state.progress.mastered[id]?'✓ Dikuasai':'Tandai';toast(state.progress.mastered[id]?'Ditandai dikuasai':'Dibatalkan')});};
    ['input','change'].forEach(ev=>$$(`#vSearch,#vChapter,#vCategory`).forEach(el=>el.addEventListener(ev,run)));run();
  }

  function renderQuizSetup(ch){const c=chapter(ch)||chapters[0];navActive('chapters');markOpened(c.id);const avail=chVocab(c.id).length;
    $('#main').innerHTML=`<section class="section quiz-shell"><div class="section-head"><div><div class="eyebrow">BAB ${String(c.id).padStart(2,'0')}</div><h2>${esc(c.titleKo)}</h2><p>${esc(c.titleId)} · ${avail} kosakata</p></div><a class="btn" href="#chapters">Kembali</a></div><div class="card settings-card"><label>Jumlah soal<select id="qCount" class="select"><option value="10">10</option><option value="20">20</option><option value="30">30</option><option value="50">50</option><option value="all">Semua</option></select></label><label>Mode quiz<select id="qMode" class="select"><option value="mixed">Mixed</option><option value="ko-id">Korea → Indonesia</option><option value="id-ko">Indonesia → Korea</option><option value="meaning">Pilih arti</option><option value="word">Pilih kosakata</option></select></label><label>Timer<select id="qTimer" class="select"><option value="0">OFF</option><option value="30">30 detik</option><option value="60">60 detik</option><option value="90">90 detik</option></select></label><div class="actions"><button id="startQuiz" class="btn primary">Mulai Quiz</button></div><p class="small">Jika jumlah soal melebihi kosakata yang tersedia, sistem memakai seluruh kosakata yang ada.</p></div></section>`;
    $('#qCount').value=state.settings.questionCount;$('#qMode').value=state.settings.quizMode;$('#qTimer').value=String(state.settings.timer);
    $('#startQuiz').onclick=()=>{state.settings.questionCount=$('#qCount').value;state.settings.quizMode=$('#qMode').value;state.settings.timer=Number($('#qTimer').value);save();startQuiz(c.id)};
  }
  function generateQuestion(v,mode,list){let type=mode;if(type==='mixed')type=shuffle(['ko-id','id-ko','meaning','word'])[0];const isKR=type==='ko-id'||type==='meaning';const prompt=isKR?v.korean:v.indonesian;const correct=isKR?v.indonesian:v.korean;const seen=new Set([correct]);const distractors=[];for(const d of shuffle(list.filter(x=>x.id!==v.id))){const val=isKR?d.indonesian:d.korean;if(!seen.has(val)){seen.add(val);distractors.push(val)}if(distractors.length>=3)break}const choices=shuffle([correct,...distractors]);return {v,type,prompt,correct,choices,user:null,correctAns:correct}
  }
  function startQuiz(ch){const list=chVocab(ch);let n=state.settings.questionCount==='all'?list.length:Math.min(Number(state.settings.questionCount)||10,list.length);const selected=shuffle(list).slice(0,n);state.quiz={chapter:ch,questions:selected.map(v=>generateQuestion(v,state.settings.quizMode,list)),index:0,correct:0,answers:[],startedAt:Date.now(),timer:null,remaining:state.settings.timer,locked:false};renderQuiz();}
  function questionTypeLabel(t){return {'ko-id':'Korea → Indonesia','id-ko':'Indonesia → Korea','meaning':'Pilih arti','word':'Pilih kosakata'}[t]||t}
  function renderQuiz(){if(!state.quiz){location.hash='#chapters';return}const q=state.quiz.questions[state.quiz.index];const total=state.quiz.questions.length;clearInterval(state.quiz.timer);state.quiz.remaining=state.settings.timer;state.quiz.locked=false;
    $('#main').innerHTML=`<section class="quiz-shell"><div class="quiz-top"><div><strong>Bab ${state.quiz.chapter}</strong><div class="small">Soal ${state.quiz.index+1} / ${total}</div></div><div class="timer" id="timer">${state.settings.timer?`${state.settings.timer}s`:'OFF'}</div></div><div class="quiz-progress" style="margin-top:10px"><div style="width:${((state.quiz.index)/total)*100}%"></div></div><article class="quiz-card"><div class="question-type">${questionTypeLabel(q.type)}</div><div class="question">${esc(q.prompt)}</div><div class="answers">${q.choices.map((c,i)=>`<button class="answer" data-answer="${esc(c)}"><span>${String.fromCharCode(65+i)}.</span> ${esc(c)}</button>`).join('')}</div><div id="feedback"></div></article></section>`;
    $$('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));if(state.settings.timer)runTimer();
  }
  function runTimer(){const el=$('#timer');state.quiz.timer=setInterval(()=>{state.quiz.remaining--;if(el)el.textContent=`${Math.max(0,state.quiz.remaining)}s`;if(state.quiz.remaining<=5)el?.classList.add('danger');if(state.quiz.remaining<=0){clearInterval(state.quiz.timer);answer(null,true)}},1000)}
  function answer(value,timedOut=false){if(state.quiz.locked)return;state.quiz.locked=true;clearInterval(state.quiz.timer);const q=state.quiz.questions[state.quiz.index];const ok=value!==null&&value===q.correctAns;q.user=value;q.timedOut=timedOut;state.quiz.answers.push({id:q.v.id,prompt:q.prompt,type:q.type,user:value,correct:q.correctAns,ok,timedOut});if(ok){state.quiz.correct++;state.progress.streak=(state.progress.streak||0)+1;state.progress.bestStreak=Math.max(state.progress.bestStreak,state.progress.streak);award(10+Math.min(40,(state.progress.streak-1)*10));state.progress.learned[q.v.id]=true}else{state.progress.streak=0;state.progress.learned[q.v.id]=true}save();$$('.answer').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.correctAns)b.classList.add('correct');if(value!==null&&b.dataset.answer===value&&!ok)b.classList.add('wrong')});const f=$('#feedback');if(f)f.innerHTML=`<div class="feedback"><h3>${ok?'정답! 🎉':'오답'}</h3><div>${ok?'Jawaban benar!':'Jawaban salah.'}${timedOut?' Waktu habis.':''}</div><div class="small" style="margin-top:7px">Jawaban kamu: <strong>${esc(value??'—')}</strong><br>Jawaban benar: <strong>${esc(q.correctAns)}</strong></div><button id="nextQ" class="btn primary" style="margin-top:12px">${state.quiz.index+1===state.quiz.questions.length?'Lihat Hasil':'Lanjut →'}</button></div>`;$('#nextQ').onclick=nextQuestion}
  function nextQuestion(){if(state.quiz.index+1>=state.quiz.questions.length){finishQuiz();return}state.quiz.index++;renderQuiz()}
  function finishQuiz(){const q=state.quiz;const total=q.questions.length,score=Math.round(q.correct/total*100);if(total){award(50);if(score===100)award(100,'Perfect Score')}const elapsed=(Date.now()-q.startedAt)/1000;state.history.push({date:new Date().toISOString(),chapter:q.chapter,score,correct:q.correct,total,mode:state.settings.quizMode,timer:state.settings.timer,elapsed,answers:q.answers});state.progress.highestScore=Math.max(state.progress.highestScore||0,score);checkAchievements();save();state.quiz.result={score,correct:q.correct,total,elapsed};location.hash='#results'}
  function renderResults(){const r=state.quiz?.result||state.history[state.history.length-1];if(!r){location.hash='#home';return}const c=chapter(state.quiz?.chapter||state.history[state.history.length-1].chapter);navActive('chapters');$('#main').innerHTML=`<section class="quiz-shell"><div class="card"><div class="eyebrow">HASIL QUIZ</div><h2 style="text-align:center">${esc(c.titleKo)}</h2><div class="result-score" id="scoreAnim">0%</div><div class="grid stats-grid"><div class="card"><div class="stat-number">${r.correct}</div><div class="stat-label">Benar</div></div><div class="card"><div class="stat-number">${r.total-r.correct}</div><div class="stat-label">Salah</div></div><div class="card"><div class="stat-number">${r.score}%</div><div class="stat-label">Akurasi</div></div><div class="card"><div class="stat-number">${fmtTime(r.elapsed)}</div><div class="stat-label">Waktu</div></div></div><div class="actions" style="margin-top:18px"><button id="repeat" class="btn primary">Ulangi Quiz</button><a class="btn secondary" href="#review">Review Jawaban</a><a class="btn" href="#chapters">Kembali ke Bab</a><a class="btn" href="#quiz?chapter=${c.id<30?c.id+1:1}">Quiz Bab Berikutnya</a></div></div></section>`;$('#repeat').onclick=()=>startQuiz(c.id);animateScore(r.score)}
  function animateScore(target){let n=0;const el=$('#scoreAnim');const step=()=>{n=Math.min(target,n+Math.max(1,Math.ceil(target/30)));if(el)el.textContent=n+'%';if(n<target)requestAnimationFrame(step)};requestAnimationFrame(step)}
  function renderReview(){const h=state.history[state.history.length-1];if(!h){location.hash='#home';return}navActive('chapters');const q=h.answers||[];$('#main').innerHTML=`<section class="quiz-shell section"><div class="section-head"><div><h2>Review Jawaban</h2><p>Bab ${h.chapter} · ${h.score}%</p></div><a class="btn" href="#results">Kembali</a></div>${q.map((x,i)=>`<article class="review-item"><div class="small">Soal ${i+1} · ${questionTypeLabel(x.type)}</div><div class="korean">${esc(x.prompt)}</div><div class="sub">Jawaban kamu: <strong>${esc(x.user??'—')}</strong></div><div class="sub">Jawaban benar: <strong>${esc(x.correct)}</strong></div><div style="margin-top:8px"><span class="badge ${x.ok?'good':'bad'}">${x.ok?'Benar':'Salah'}</span></div></article>`).join('')}</section>`}

  function renderFlashcards(){navActive('flashcards');const q=new URLSearchParams(location.hash.split('?')[1]||'');const ch=Number(q.get('chapter')||0);const list=ch?vocabulary.filter(v=>v.chapter===ch):vocabulary;if(!state.flash||state.flash.chapter!==ch||state.flash.listIds?.join()!=list.map(x=>x.id).join()){state.flash={chapter:ch,index:0,flipped:false,listIds:list.map(x=>x.id)}}const v=list[state.flash.index]||list[0];if(!v){$('#main').innerHTML='<div class="empty">Belum ada kartu.</div>';return}markOpened(ch||1);$('#main').innerHTML=`<section class="flashcard-wrap"><div class="section-head"><div><div class="eyebrow">FLASHCARDS</div><h2>${ch?'Bab '+ch:'Semua Bab'}</h2><p>Kartu ${state.flash.index+1} / ${list.length}</p></div><select id="fcChapter" class="select" style="max-width:240px"><option value="0">Semua Bab</option>${chapters.map(c=>`<option value="${c.id}" ${ch===c.id?'selected':''}>Bab ${c.id} — ${esc(c.titleKo)}</option>`).join('')}</select></div><div class="flashcard ${state.flash.flipped?'flipped':''}" id="flashCard"><div class="flashcard-inner"><div class="fc-face"><div><div class="small">Depan</div><div class="fc-word">${esc(v.korean)}</div><div class="small">Bab ${v.chapter}</div></div></div><div class="fc-face fc-back"><div><div class="small">Arti Bahasa Indonesia</div><div class="fc-word">${esc(v.korean)}</div><div class="fc-meaning">${esc(v.indonesian)}</div><div class="small">${esc(v.categoryKo)}</div></div></div></div></div><div class="actions" style="margin-top:14px;justify-content:center"><button class="btn" id="prev">← Sebelumnya</button><button class="btn primary" id="flip">Balik</button><button class="btn" id="next">Berikutnya →</button></div><div class="actions" style="margin-top:10px;justify-content:center"><button class="btn secondary" id="known">✓ Sudah hafal</button><button class="btn" id="study">☆ Tandai untuk dipelajari</button><button class="btn danger" id="unlearn">Belum hafal</button></div><div class="card" style="margin-top:14px"><div class="small">Status kartu</div><strong>${state.progress.flashcards[v.id]||'belum ditandai'}</strong></div></section>`;
    $('#fcChapter').onchange=e=>{location.hash=`#flashcards?chapter=${e.target.value}`};$('#flip').onclick=()=>{state.flash.flipped=!state.flash.flipped;renderFlashcards()};$('#prev').onclick=()=>{state.flash.index=(state.flash.index-1+list.length)%list.length;state.flash.flipped=false;renderFlashcards()};$('#next').onclick=()=>{state.flash.index=(state.flash.index+1)%list.length;state.flash.flipped=false;award(5);save();renderFlashcards()};$('#known').onclick=()=>{state.progress.flashcards[v.id]='known';state.progress.learned[v.id]=true;state.progress.mastered[v.id]=true;award(5);save();toast('Kartu dikuasai')};$('#study').onclick=()=>{state.progress.flashcards[v.id]='study';state.progress.learned[v.id]=true;save();toast('Ditandai untuk dipelajari')};$('#unlearn').onclick=()=>{state.progress.flashcards[v.id]='new';state.progress.mastered[v.id]=false;save();toast('Ditandai belum hafal')};
  }

  function renderStatistics(){navActive('statistics');checkAchievements();$('#main').innerHTML=`<section class="section"><div class="section-head"><div><h2>Statistics</h2><p>Progress belajar tersimpan lokal di browser.</p></div><button id="resetData" class="btn danger">Reset Progress</button></div><div class="grid stats-grid">${statCard(totalLearned(),'Vocabulary Dipelajari')}${statCard(totalMastered(),'Vocabulary Dikuasai')}${statCard((state.progress.highestScore||0)+'%','Highest Score')}${statCard((state.progress.xp||0)+' XP','XP')}${statCard(xpLevel(),'Level')}${statCard(state.progress.streak||0,'Streak Saat Ini')}${statCard(state.progress.bestStreak||0,'Streak Terbaik')}${statCard(state.progress.openedChapters.length,'Bab Dibuka')}</div><section class="section"><div class="section-head"><div><h2>Achievement</h2><p>Achievement berdasarkan aktivitas yang benar-benar tercatat.</p></div></div><div class="grid">${achievement('firstQuiz','First Quiz','Selesaikan quiz pertama')}${achievement('streak10','10 Streak','10 jawaban benar berturut-turut')}${achievement('chapterMaster','Chapter Master','Kuasai seluruh kosakata dalam satu bab')}${achievement('perfect','Perfect Score','Dapatkan 100% pada quiz')}${achievement('explorer','Vocabulary Explorer','Buka vocabulary dari minimal 5 bab')}</div></section><section class="section"><h2>Progress per Bab</h2><div style="height:10px"></div><div class="grid">${chapters.map(c=>`<div class="card"><div style="display:flex;justify-content:space-between"><strong>Bab ${c.id}</strong><span>${progressFor(c.id)}%</span></div><div class="progress-track" style="margin-top:9px"><div class="progress-fill" style="width:${progressFor(c.id)}%"></div></div><div class="small" style="margin-top:7px">${chVocab(c.id).length} kosakata</div></div>`).join('')}</div></section></section>`;$('#resetData').onclick=()=>{if(confirm('Reset semua progress dan riwayat quiz?')){localStorage.removeItem(KEY_PROGRESS);localStorage.removeItem(KEY_SETTINGS);localStorage.removeItem(KEY_HISTORY);location.reload()}}
  }
  function achievement(key,title,desc){const ok=!!state.progress.achievements[key];return `<div class="card"><div class="badge ${ok?'good':'bad'}">${ok?'✓ Terbuka':'🔒 Terkunci'}</div><h3>${title}</h3><div class="small">${desc}</div></div>`}

  $('#themeToggle').onclick=()=>{state.settings.darkMode=!state.settings.darkMode;save();setTheme()};window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);window.addEventListener('keydown',e=>{if(state.quiz&&!state.quiz.locked&&['1','2','3','4'].includes(e.key)){const b=$$('[data-answer]')[Number(e.key)-1];b?.click()}});
})();
